DROP TABLE IF EXISTS la_member;
DROP TABLE IF EXISTS la_blog;

CREATE TABLE la_member
(
    MEMBER_ID   VARCHAR(255) PRIMARY KEY,
    USERNAME    VARCHAR(255) NOT NULL,
    EMAIL       VARCHAR(255) NOT NULL,
    PASSWORD    VARCHAR(255) NOT NULL,
    ENABLED      BOOLEAN NOT NULL DEFAULT FALSE,
    ROLE        VARCHAR(255) NOT NULL,
    CREATED_AT  DATETIME,
    UPDATED_AT  DATETIME
);

CREATE TABLE la_blog
(
    ID              BIGINT AUTO_INCREMENT PRIMARY KEY,
    TITLE           VARCHAR(255) NOT NULL,
    CONTENT         VARCHAR(255) NOT NULL,
    CREATED_AT      DATETIME,
    UPDATED_AT      DATETIME,
    AUTHOR          VARCHAR(255) NOT NULL
);
